groups:
  - name: lach-system-alerts
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      # High order processing time
      - alert: HighOrderProcessingTime
        expr: histogram_quantile(0.95, rate(order_processing_duration_seconds_bucket[5m])) > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High order processing time"
          description: "95th percentile order processing time is {{ $value }} seconds"

      # Queue backlog
      - alert: QueueBacklog
        expr: increase(orders_created_total[5m]) - increase(order_status_changes_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Order queue backlog detected"
          description: "Queue backlog is {{ $value }} orders"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: active_connections < 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection issues"
          description: "No active database connections for service {{ $labels.service }}"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / container_memory_usage_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"

      # High CPU usage
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%" 