global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:5003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'production-queue-service'
    static_configs:
      - targets: ['production-queue-service:5004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:5005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'whatsapp-service'
    static_configs:
      - targets: ['whatsapp-service:5006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 30s 